version: "3.1" 
services:
  glm_test:
    image: wdwatkins/glm3r:v0.2
    build:
      context: .
    ports:
      - "8787:8787"
    volumes:
      - data:/home/rstudio/glm3_test                                                                                              
    environment:
      - ROOT=TRUE
      - PASSWORD=mypass

volumes:
  data:

